### ISSUE TITLE
What Pages are we going to need?

### ISSUE THREAD

**Issue by kmccloskey** [kmccloskey/valship#10]
Log In
Sign Up
Profile
    \* See all Current Jobs
    \* Sign Out
Create New Boat
View a Boat and all it's information
Create New Job
View a Job
Create New Assignment for a boat
Edit Profile
    \* Delete User
    \* Edit profile information

Let me know your thoughts

**Comment by jesusmorenoo** [comment]
Done with Log in, Sign up, Sign out, Create New Boat, Create a new job, edit profile, Delete User, Edit profile information

**Comment by jesusmorenoo** [comment]
What's left is See jobs person created, and boats created by user.
